---
title: "Code of Conduct"
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

In order to foster an open, safe and friendly environment, we, the organizers, are committed to making participation in PIISCO workshop a harassment-free experience for all people, regardless of sex, identity, gender, age, sexual orientation, disability, physical appearance, body size, nationality, race, ethnicity, religion (or lack thereof), ideology or technological options.

## Our standards

We do not tolerate harassment at PIISCO's workshops in any form.

**Examples of behaviors that contribute to creating a positive environment for our community:**
 
* Demonstrating empathy and kindness to others**
* Respecting different opinions, points of view, and experiences
* Giving and accepting appropriate constructive feedback
* Accepting responsibility and apologising to those we affect for our mistakes, learning from experience
* Focusing on what is best not only for us as individuals, but for the community at large

**Examples of unacceptable behavior:**

* Using sexualized language or images as well as any unwanted sexual attention or advances
* Derogatory comments (trolling), insults and personal or political attacks
* Any kind of harassment in public or private
* Publishing other people’s private information, such as physical or e-mail addresses, without their explicit permission
* Other conduct that may reasonably be considered inappropriate in a professional setting

## Our responsibilities

Those of us who organize the workshop are responsible for clarifying standards of acceptable behavior and reserve the right of admission or permanence, temporarily or permanently, in the workshop for any behavior we consider unacceptable.

We also have the responsibility and reserve the right to remove, edit or reject comments, materials and other contributions that are not in line with this Code of Conduct.

## Scope

This code of conduct applies to all spaces related to the workshop This includes our email account, our Slack, our workshops through Meet, our GitHub organization and all its repositories, and any other part of the workshop

## Application

Cases of abusive, harassing, or unacceptable behavior can be reported by sending an email to sistemascomplejosungs@gmail.com All messages will be reviewed and investigated and will result in whatever response the founders deem necessary and appropriate to the circumstances.

Founders will respect the privacy and safety of those who report incidents.

## Attribution

This Code of Conduct is adapted from Contributor Covenant, version 2.0, available at https://www.contributor-covenant.org/es/version/2/0/code_of_conduct.html.




